name = "FluxRC"
uuid = "19bbc782-a6fb-447a-8120-ff40275555e1"
authors = ["Tianbai Xiao <tianbaixiao@gmail.com>"]
version = "0.1.0"

[deps]
FastGaussQuadrature = "442a2c76-b920-505d-bb47-c5924d526838"
GSL = "92c85e6c-cbff-5e0c-80f7-495c94daaecd"
KitBase = "86eed249-3a28-466f-8d3a-596821e1af9a"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
TerminalLoggers = "5d786b92-1e48-4d6f-9151-6b4477ca9bed"

[compat]
FastGaussQuadrature = "0.2, 0.3, 0.4"
GSL = "^1"
KitBase = "0.3"
OffsetArrays = "^1"
OrdinaryDiffEq = "^5"
TerminalLoggers = "0.1"
julia = "^1"
